export const AI_TASKS = {
  GENERATE_LESSON: "GENERATE_LESSON",
  GENERATE_VOCABULARY: "GENERATE_VOCABULARY",
  GENERATE_GRAMMAR: "GENERATE_GRAMMAR",
  GENERATE_DIALOGUE: "GENERATE_DIALOGUE",
  GENERATE_READING: "GENERATE_READING",
  GENERATE_EXERCISES: "GENERATE_EXERCISES",
  GENERATE_QUIZ: "GENERATE_QUIZ",
  EVALUATE_ANSWER: "EVALUATE_ANSWER",
  EXPLAIN_MISTAKE: "EXPLAIN_MISTAKE",
  GENERATE_FLASHCARDS: "GENERATE_FLASHCARDS",
  GENERATE_STUDY_PLAN: "GENERATE_STUDY_PLAN",
} as const;

export type AITask = (typeof AI_TASKS)[keyof typeof AI_TASKS];
